### ISSUE TITLE
Allow using secondary type names in schemas

### ISSUE THREAD

**Issue by eduardbosch** [TonyStark106/SwiftFlatBuffers#1]
Hi,

First of all, thanks a lot for this library. It allows using flatbuffers with swift really easy.

I think that could be good to allow using the secondary type names in the schemas. By secondary names I mean the names in parenthesis in the types section here https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html

I had a schema that used `uint8` and I had to change it to `ubyte` in order to compile.

**Comment by TonyStark106** [comment]
I am really sorry for the late response. I 've update newewst flatbuffers version to fix this issue. thx :)

**Comment by eduardbosch** [comment]
Thanks! It works like a charm! 🎉

Did you know if this library could be merged with FlatBuffers to allow Swift official support?

It's being discussed here https://github.com/google/flatbuffers/issues/3785#issuecomment-382780634

This library makes life easier with FlatBuffers and Swift!
